Loading training set...

Num images:  6
Image shape: [3, 256, 256]
Label shape: [0]

Constructing networks...
Traceback (most recent call last):
  File "train.py", line 648, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "D:\SDK\Python\venv\mat-3.7\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\SDK\Python\venv\mat-3.7\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\SDK\Python\venv\mat-3.7\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\SDK\Python\venv\mat-3.7\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\SDK\Python\venv\mat-3.7\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 641, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 471, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "D:\MAT\training\training_loop.py", line 152, in training_loop
    G = dnnlib.util.construct_class_by_name(**G_kwargs, **common_kwargs).train().requires_grad_(False).to(device) # subclass of torch.nn.Module
  File "D:\SDK\Python\venv\mat-3.7\lib\site-packages\torch\nn\modules\module.py", line 612, in to
    return self._apply(convert)
  File "D:\SDK\Python\venv\mat-3.7\lib\site-packages\torch\nn\modules\module.py", line 359, in _apply
    module._apply(fn)
  File "D:\SDK\Python\venv\mat-3.7\lib\site-packages\torch\nn\modules\module.py", line 359, in _apply
    module._apply(fn)
  File "D:\SDK\Python\venv\mat-3.7\lib\site-packages\torch\nn\modules\module.py", line 359, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "D:\SDK\Python\venv\mat-3.7\lib\site-packages\torch\nn\modules\module.py", line 381, in _apply
    param_applied = fn(param)
  File "D:\SDK\Python\venv\mat-3.7\lib\site-packages\torch\nn\modules\module.py", line 610, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: unknown error
